DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS BOOKINFO;
DROP TABLE IF EXISTS SERIESBOOK;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS BORROWHISTORY;


CREATE TABLE BOOK (
	ID VARCHAR(16)  NOT NULL PRIMARY KEY,
	CREATE_DATETIME TIMESTAMP,
	STATUS VARCHAR(8),  
	BORROWER_ID VARCHAR(16),
	BORROW_DATETIME TIMESTAMP,
	BORROW_COUNT INT );

CREATE TABLE BOOKINFO (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	CATEGORY VARCHAR(8) NOT NULL DEFAULT 'BOOK',  
	ISBN VARCHAR(13),
	NAME VARCHAR(100) NOT NULL,
	SUB_NAME VARCHAR(100),
	PRESS VARCHAR(50),
	SERIES_ID VARCHAR(16), 
	PUBLISH_DATETIME TIMESTAMP,
	DESCRIPTION TEXT(150),
	PRICE DECIMAL(7,2),
	COVER BLOB,
	TAGS VARCHAR(900),
	RATE DECIMAL(3,1) );

CREATE TABLE SERIESBOOK (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	PRESS VARCHAR(50),
	VOLUME_NUM INT
	PRICE DECIMAL(7,2) );

CREATE TABLE USER (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	GENDER VARCHAR(8), 
	PASSWORD VARCHAR(20));

CREATE TABLE BORROWHISTORY(
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	BOOK_ID VARCHAR(16),
	USER_ID VARCHAR(16),
	ACTION VARCHAR(8),
	CREATE_DATETIME TIMESTAMP );
