
CREATE TABLE BOOK (
	ID VARCHAR(16)  NOT NULL PRIMARY KEY,
	CREATE_DATE DATETIME,
	STATUS VARCHAR(8),
	BORROWER_ID VARCHAR(16),
	BORROW_DATE DATETIME,
	BORROW_COUNT INT,
	TAGS VARCHAR(900) );

CREATE TABLE BOOKINFO (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	ISBN VARCHAR(13),
	HEAD_NAME VARCHAR(100) NOT NULL,
	SUB_HEADING VARCHAR(100),
	PRESS VARCHAR(50),
	PUBLISH_DATE DATETIME,
	DESCRIPTION TEXT(150),
	PRICE INT,
	COVER VARCHAR(150) );

