
CREATE TABLE BOOK (
	ID VARCHAR(16)  NOT NULL PRIMARY KEY,
	TYPE VARCHAR(8) NOT NULL DEFAULT 'BOOK', --CODETABLE 'BTY'
	CREATE_DATE DATETIME,
	STATUS VARCHAR(8), --CODETABLE 'BST'
	BORROWER_ID VARCHAR(16),
	BORROW_DATE DATETIME,
	BORROW_COUNT INT );

CREATE TABLE BOOKINFO (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	ISBN VARCHAR(13),
	HEAD_NAME VARCHAR(100) NOT NULL,
	SUB_HEADING VARCHAR(100),
	PRESS VARCHAR(50),
	SERIES_ID VARCHAR(16), 
	PUBLISH_DATE DATETIME,
	DESCRIPTION TEXT(150),
	PRICE FLOAT,
	COVER VARCHAR(150),
	TAGS VARCHAR(900),
	RATE FLOAT  );

CREATE TABLE SERIESBOOK (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	PRESS VARCHAR(50),
	VOLUME_NUM INT
	PRICE FLOAT );


